/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.ModelSessaoUsuario;
import model.ModelUsuario;
import controller.ControllerUsuario;

/**
 *
 * @author charles
 */
public class ViewPrincipal extends javax.swing.JFrame {

    ModelUsuario modelUsuario = new ModelUsuario();
    ControllerUsuario controllerUsuario = new ControllerUsuario();

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        permissaoAcesso();
        
    }
    
    private void permissaoAcesso() {
        modelUsuario = controllerUsuario.getUsuarioController(new ModelSessaoUsuario().codigo);
        
        if (modelUsuario.getPerm_cad_empresa() == 0) {
            miCadEmpresa.setEnabled(false);
            
        } else if (modelUsuario.getPerm_cad_empresa() == 1) {
            miCadEmpresa.setEnabled(true);
        }
        if (modelUsuario.getPerm_cad_usuario() == 0) {
            miCadUsuario.setEnabled(false);
            
        } else if (modelUsuario.getPerm_cad_usuario() == 1) {
            miCadUsuario.setEnabled(true);
        }
        if (modelUsuario.getPerm_cad_usuario() == 0) {
            miCadUsuario.setEnabled(false);
            
        } else if (modelUsuario.getPerm_cad_usuario() == 1) {
            miCadUsuario.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jmbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadUsuario = new javax.swing.JMenuItem();
        Aspirante = new javax.swing.JMenuItem();
        jmOrigemAluno = new javax.swing.JMenuItem();
        jmFormacaoBasica = new javax.swing.JMenuItem();
        jmMaterias = new javax.swing.JMenuItem();
        jmTurma = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmSalas = new javax.swing.JMenuItem();
        miCadEmpresa = new javax.swing.JMenuItem();
        jmCargo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmTipoAdms = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP Owl - www.centersolutionsti.com.br");
        setResizable(false);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(lbLogo)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbLogo)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miCadUsuario.setText("Usuarios");
        miCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(miCadUsuario);

        Aspirante.setText("Geral");
        Aspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AspiranteActionPerformed(evt);
            }
        });
        jMenu1.add(Aspirante);

        jmOrigemAluno.setText("Origem do aluno");
        jmOrigemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmOrigemAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(jmOrigemAluno);

        jmFormacaoBasica.setText("Formação básica");
        jmFormacaoBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormacaoBasicaActionPerformed(evt);
            }
        });
        jMenu1.add(jmFormacaoBasica);

        jmMaterias.setText("Materias");
        jmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(jmMaterias);

        jmTurma.setText("Turma");
        jmTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(jmTurma);

        jMenuItem2.setText("Horários");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jmSalas.setText("Salas");
        jmSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalasActionPerformed(evt);
            }
        });
        jMenu1.add(jmSalas);

        miCadEmpresa.setText("Empresas");
        miCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadEmpresa);

        jmCargo.setText("Cargo");
        jmCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargoActionPerformed(evt);
            }
        });
        jMenu1.add(jmCargo);

        jMenuItem1.setText("Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jmTipoAdms.setText("Tipo de admissão");
        jmTipoAdms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTipoAdmsActionPerformed(evt);
            }
        });
        jMenu1.add(jmTipoAdms);

        jMenuItem4.setText("Cadastro de CBO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Dias de cursos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Carga horária de curso");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Local de aprendizagem");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Periodo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Dias intensivo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Intensivo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("Dia de atividade teórica");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jmbMenu.add(jMenu1);

        jMenu3.setText("Encaminhamento");

        jMenuItem3.setText("Encaminhamento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jmbMenu.add(jMenu3);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadEmpresaActionPerformed
        new ViewEmpresa().setVisible(true);
    }//GEN-LAST:event_miCadEmpresaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadUsuarioActionPerformed
        new ViewCadUsuario().setVisible(true);
        
    }//GEN-LAST:event_miCadUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ViewHoras().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmOrigemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmOrigemAlunoActionPerformed
        new ViewOrigemAluno().setVisible(true);
    }//GEN-LAST:event_jmOrigemAlunoActionPerformed

    private void jmCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargoActionPerformed
        new ViewCargo().setVisible(true);
    }//GEN-LAST:event_jmCargoActionPerformed

    private void jmFormacaoBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormacaoBasicaActionPerformed
        new ViewFomacaoBasica().setVisible(true);
        
    }//GEN-LAST:event_jmFormacaoBasicaActionPerformed

    private void jmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriasActionPerformed
        new ViewCadMateria().setVisible(true);
    }//GEN-LAST:event_jmMateriasActionPerformed

    private void jmTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTurmaActionPerformed
        new ViewTurma().setVisible(true);
    }//GEN-LAST:event_jmTurmaActionPerformed

    private void jmSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalasActionPerformed
        new ViewSala().setVisible(true);
    }//GEN-LAST:event_jmSalasActionPerformed

    private void AspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AspiranteActionPerformed
        new ViewAspirante().setVisible(true);
    }//GEN-LAST:event_AspiranteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new ViewEncaminhamento().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmTipoAdmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTipoAdmsActionPerformed
        new ViewCadAdmissao().setVisible(true);
    }//GEN-LAST:event_jmTipoAdmsActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new ViewCadCBO().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new ViewDiaCurso().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new ViewHorasTrabalhadas().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new ViewLocalAprendizagem().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new ViewPeriodo().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new ViewDiasIntensivo().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new ViewIntensivo().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new ViewDiaAtivTeorica().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aspirante;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmCargo;
    private javax.swing.JMenuItem jmFormacaoBasica;
    private javax.swing.JMenuItem jmMaterias;
    private javax.swing.JMenuItem jmOrigemAluno;
    private javax.swing.JMenuItem jmSalas;
    private javax.swing.JMenuItem jmTipoAdms;
    private javax.swing.JMenuItem jmTurma;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenuItem miCadEmpresa;
    private javax.swing.JMenuItem miCadUsuario;
    // End of variables declaration//GEN-END:variables
}
